name: "Run tests"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0, 7.4, 7.3, 7.2, 7.1]
        laravel: [10.0, 9.0, 8.0, 7.0, 6.0, 5.8]
        dependency-version: [lowest, stable]
        include:
          - laravel: 10.0
            testbench: 8.0
          - laravel: 9.0
            testbench: 7.0
          - laravel: 8.0
            testbench: 6.23
          - laravel: 7.0
            testbench: 5.20
          - laravel: 6.0
            testbench: 4.18
          - laravel: 5.8
            testbench: 3.8
        exclude:
            - laravel: 10.0
              php: 8.0
            - laravel: 10.0
              php: 7.4
            - laravel: 10.0
              php: 7.3
            - laravel: 10.0
              php: 7.2
            - laravel: 10.0
              php: 7.1
            - laravel: 9.0
              php: 7.4
            - laravel: 9.0
              php: 7.3
            - laravel: 9.0
              php: 7.2
            - laravel: 9.0
              php: 7.1
            - laravel: 8.0
              php: 7.2
            - laravel: 8.0
              php: 7.1
            - laravel: 7.0
              php: 8.1
            - laravel: 7.0
              php: 7.1
            - laravel: 6.0
              php: 8.1
            - laravel: 6.0
              php: 7.1
            - laravel: 5.8
              php: 8.1
            - laravel: 5.8
              php: 8.0

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }} / Prefer ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}" "orchestra/testbench:^${{ matrix.testbench }}" "mockery/mockery:^1.3.2" --no-interaction --no-update
          composer update --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/phpunit --testdox
